# Generated by Django 2.0.13 on 2019-05-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yebon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='happythings',
            name='effortIndex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='happythings',
            name='happinessIndex',
            field=models.IntegerField(default=0),
        ),
    ]
